version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: ordemplus_sqlserver
    restart: always
    environment:
      SA_PASSWORD: "OrdemPlus@2025"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

  api:
    build:
      context: ./OrdemPlusAPI
      dockerfile: Dockerfile
    container_name: ordemplus_api
    restart: always
    depends_on:
      - sqlserver
    environment:
      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=OrdemPlus;User Id=sa;Password=OrdemPlus@2025;TrustServerCertificate=True;"
    ports:
      - "5000:5000"
      - "5001:5001"
    networks:
      - app_network

volumes:
  sqlserver_data:

networks:
  app_network:
    driver: bridge
